library(testthat)
test_file("testthat/test_influence_functions.R")
test_file("testthat/test_local_polynomials.R")
test_file("testthat/test_nuisance.R")
test_file("testthat/test_load_nprobust.R")
test_file("testthat/test_debiased_inference.R")
